services:
  #mysql
  bdcontainer:
    container_name: dbtpfinal
    image: mysql:latest
    # healthcheck:
    #   test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
    #   timeout: 20s
    #   retries: 10
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass2024
      - MYSQL_DATABASE=dbtpfinal
    volumes:
      - vol_mysql:/var/lib/mysql
    networks:
      - rede_bd

  #phpmyadmin
  bgguicontainer:
    container_name: bgguicontainer
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=dbtpfinal
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=pass2024
    depends_on:
      - bdcontainer
    networks:
      - rede_bd
    
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "4444:4444"
    depends_on:
      - bdcontainer
      # - migrate
    networks:
      - rede_bd

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8000:80"
    depends_on:
      - bdcontainer
    networks:
      - rede_bd

  # migrate:
  #   container_name: migrate
  #   build: ./backend
  #   command: npx prisma migrate deploy 
  #   depends_on:
  #     bdcontainer:
  #       condition: service_healthy
  #   networks:
  #     - rede_bd

networks:
  rede_bd:
    driver: bridge

volumes:
  vol_mysql: